spring:
  application:
    name: jwt

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          format: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect